<?php


namespace app\modules\crud\controllers\api\resources;

use app\modules\crud\controllers\api\resources\Club;

class Equipo extends \app\modules\crud\models\Equipo
{
    public function fields()
    {
        return ['id_equipo','nombre_equipo','club','created_by']; // TODO: Change the autogenerated stub
    }



}
